export const ROUTES = {
  root: '/',
  landing: '/landing',
  access: '/access',
  onboarding: '/onboarding',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  confirmEmail: '/confirm-email',
  home: '/home',
  blisters: '/blisters',
  createBlister: '/blisters/new',
  joinBlister: '/blisters/join',
  blisterDetail: (blisterId: string) => `/blisters/${blisterId}`,
  blisterMembers: (blisterId: string) => `/blisters/${blisterId}/members`,
  blisterMedications: (blisterId: string) => `/blisters/${blisterId}/medicines`,
  addMedicine: (blisterId: string) => `/blisters/${blisterId}/medicines/add`,
  editMedicine: (blisterId: string, medicineId: string) =>
    `/blisters/${blisterId}/medicines/${medicineId}/edit`,
  blisterTreatments: (blisterId: string) => `/blisters/${blisterId}/treatments`,
  newTreatment: (blisterId: string) => `/blisters/${blisterId}/treatments/new`,
  editTreatment: (blisterId: string, treatmentId: string) =>
    `/blisters/${blisterId}/treatments/${treatmentId}/edit`,
  blisterAppointments: (blisterId: string) => `/blisters/${blisterId}/appointments`,
  newAppointment: (blisterId: string) => `/blisters/${blisterId}/appointments/new`,
  editAppointment: (blisterId: string, appointmentId: string) =>
    `/blisters/${blisterId}/appointments/${appointmentId}/edit`,
  blisterLogs: (blisterId: string) => `/blisters/${blisterId}/logs`,
  blisterNotifications: (blisterId: string) => `/blisters/${blisterId}/notifications`,
  medicineDetail: (blisterId: string, medicineId: string) =>
    `/blisters/${blisterId}/medicines/${medicineId}`,
  cimaMedicineDetail: (nregist: string) => `/medicines/cima/${nregist}`,
  treatmentDetail: (blisterId: string, treatmentId: string) =>
    `/blisters/${blisterId}/treatments/${treatmentId}`,
  notifications: '/notifications',
  profile: '/profile',
  editProfile: '/profile/edit',
  personalInfo: '/profile/edit/info',
  changePassword: '/profile/edit/password',
  deleteAccount: '/profile/edit/delete-account',
  profileAvatar: '/profile/avatar',
  accessibility: '/profile/accessibility',
  notificationSettings: '/profile/notifications',
  mcpToken: '/profile/mcp',
  mcpTokenRevoke: '/profile/mcp/revoke',
  privacy: '/privacy',
  settings: '/settings',
  mcp: '/mcp',
  notFound: '*',
} as const;
